name: ton
description: Ton Sdk for Flutter
version: 0.0.4
homepage: https://github.com/mhbdev/ton

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7
  tonutils: ^0.5.6
  pinenacl: ^0.5.1
  convert: ^3.1.1
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  http: ^1.1.2
  universal_html: ^2.2.4
  crypto: ^3.0.3
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  flutter_i18n: ^0.34.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: net.apexteam.ton
        pluginClass: TonPlugin
      ios:
        pluginClass: TonPlugin
      linux:
        pluginClass: TonPlugin
      macos:
        pluginClass: TonPlugin
      windows:
        pluginClass: TonPluginCApi
      web:
        pluginClass: TonWeb
        fileName: ton_web.dart

  assets:
    - assets/i18n/en_US.json