name: ton
description: Ton Sdk for Flutter
version: 0.0.3
homepage: https://github.com/mhbdev/ton

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: net.apexteam.ton
        pluginClass: TonPlugin
      ios:
        pluginClass: TonPlugin
      linux:
        pluginClass: TonPlugin
      macos:
        pluginClass: TonPlugin
      windows:
        pluginClass: TonPluginCApi
      web:
        pluginClass: TonWeb
        fileName: ton_web.dart
